### ISSUE TITLE
Autentication issue

### ISSUE THREAD

**Issue by olavtolo** [late4marshmellow/com.scinan.api#11]
The token expires and authentication have to be done again.

**Comment by late4marshmellow** [comment]
i've done some changes and a new version has been uploaded as test. 
Saswell currently gives me 404 not found so I am not able to properly test it. 

[Test version](https://homey.app/en-us/app/com.scinan.api/Scinan-and-Saswell-Climate-Control/test/)

**Comment by late4marshmellow** [comment]
new test version is out, https://homey.app/a/com.scinan.api/test/
it seems to be working fine, will publish it to live after some time.
